backend:
  name: git-gateway
  branch: main
media_folder: public/images/uploads
public_folder: /images/uploads
site_url: https://lglab.ca
slug:
  encoding: ascii
  clean_accents: true
collections:
- label: Pages
  label_singular: Page
  name: pages
  description: Content management for general page content.
  files:
  - label: About
    name: about
    description: Content management for the about page.
    file: content/pages/about.md
    fields:
    - label: Title
      name: title
      widget: string
    - label: Qualifications
      label_singluar: Qualification
      name: qualifications
      widget: list
      allow_add: true
    - label: Image
      name: image
      widget: image
      allow_multiple: false
    - label: Body
      name: body
      widget: markdown
- label: Gallery Images
  label_singular: Gallery Image
  name: gallery_images
  description: Images to appear in the gallery.
  create: true
  folder: content/gallery
  identifier_field: title
  slug: "{{slug}}"
  fields:
  - label: Title
    name: title
    hint: The title of the image
    widget: string
  - label: Description
    name: description
    hint: A description of the image
    widget: text
  - label: Alt Text
    name: alt
    hint: Alt text describing the image for users with screen readers, or when the image is unable to load.
    widget: text
  - label: Image
    name: image
    hint: The image file
    widget: image
    allow_multiple: false
  - label: Date published
    name: published
    hint: A date to associate with this picture. Perhaps when it was taken.
    widget: datetime
    time_format: false
    picker_utc: true
- label: Projects
  label_singular: Project
  name: projects
  description: Current projects of lglab.
  create: true
  folder: content/projects
  identifier_field: name
  slug: "{{slug}}"
  fields:
  - label: Name
    name: name
    hint: The name of the project.
    widget: string
  - label: Description
    name: description
    hint: A description of the project.
    widget: text
  - label: Alt Text
    name: alt
    hint: Alt text describing the image for users with screen readers, or when the image is unable to load.
    widget: text
  - label: Image
    name: image
    hint: An image for the project.
    widget: image
    allow_multiple: false
  # - label: Members
  #   name: members
  #   hint: Members who work on the project.
  #   widget: relation
  #   collection: Team Members
  #   search_fields: "name.first"
  #   value_field: "name.first"
  #   display_fields: "name.first"
  - label: Tags
    name: tags
    widget: list
    
